### ISSUE TITLE
Second server not showing up in client

### ISSUE THREAD

**Issue by tsulliv11** [mtoensing/Docker-Minecraft-Bedrock-Server#33]
Hello, I am trying to set up a second server on my Synology NAS.  The first server shows up on my client devices, but the second does not at all.  The second server seems to be running fine.  I tried changing the ports in the Docker container and in the server.properties file.  Is running two servers on the same NAS device possible?

**Comment by mtoensing** [comment]
Yes it is. But this is outside of the scope of the container.

**Comment by bitofanooob** [comment]
it wont show because its advertising at another port besides 19132. i fixed it by running seedll bedrockconnect server on the side. that is listning to port 19132 and the two servers running at different ports. those i join from the bedrockconnect server. perhaps  that can get u closer.  outside gets in the same.
