### ISSUE TITLE
My town is gone after update

### ISSUE THREAD

**Issue by CottoneeSwab** [mtoensing/Docker-Minecraft-Bedrock-Server#39]
I used marctv's docker image to host a Minecraft server in my Synology NAS. It has been no issue for the past 3-4 years. However the map/world changed after the latest update to 1.19.20 (I got the latest image, and selected the same minecraft folder, server properties and whitelist.json files.). After the update, everything seems fine for a few days. Then on Aug 18, my house and some other structures were cut in half as if someone sliced through the area. I thought maybe my IPad does not have enough memory to load the other half. Then a couple days later, my whole town and house I built are gone, and replaced with an ocean. I walked around the map and there is no sign of my structures and terrains etc. I didn't make any changes to my files. I used the same steps whenever the game needs a new update. I didn't do any backup as I thought it's my server, my files, they are always safe in NAS. Can you advise what happened? and if there is any way to get back my previous map/town? I tried using an old server file that I saved 1 year ago, but when I launched it with 1.19.20, the world still seemed to have changed. I am very sure I built my houses more than 1 year ago but they are not there, and the location of my spawn is a random village.

Please advise.

**Comment by mtoensing** [comment]
_I didn't do any backup as I thought it's my server, my files, they are always safe in NAS._ 

I know this is hard, but please always do backups. It is so easy on a Synology NAS with various options. My guess is that your files got corrupted because of a crash of the client and now everything is gone. There can be so many reasons why this happened, but can't provide support the server or it's behavior. I only provide the distribution of the binaries in a docker container. This has nothing to do with that. I am very, very please sorry for your loss. =( Please make a daily ackup from now on.

**Comment by mtoensing** [comment]
I run several instances and all run well without any problem. It is not a problem with the container.

**Comment by CottoneeSwab** [comment]
Sigh...lesson learned. Thank you for confirming that nothing can be retrieved anymore.
For future reference, can you advise which files I need to backup? Is it everything in the /docker/bedrockserver/ folder?
If the files get corrupted again, do I just replace all those files with the backups and relaunch?

**Comment by mtoensing** [comment]
Yes.

**Comment by CottoneeSwab** [comment]
Thank you for your help.
And thank you for creating and maintaining this minecraft docker!
